@file:OptIn(kotlin.js.ExperimentalWasmJsInterop::class)

package io.github.youndie.shashki.rider

import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.window.ComposeViewport
import kotlinx.browser.document
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob

/**
 * The rider bundle's entry point.
 *
 * **The server is wherever this page came from.** A bundle served beside the API needs no
 * configuration to find it, and a hard-coded address would be the first thing to go wrong on a
 * deployment that is not somebody's laptop.
 */
@OptIn(ExperimentalComposeUiApi::class)
public fun main() {
    val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    ComposeViewport(document.body!!) {
        RiderApp(
            config =
                RiderConfig(
                    serverUrl = origin(),
                    riderId = "rider-1",
                    paymentMethodId = "card-4417",
                    tilesUrl = tilesUrl().takeIf { it.isNotBlank() },
                    katcherUrl = katcherUrl().takeIf { it.isNotBlank() },
                    katcherAppKey = katcherAppKey().takeIf { it.isNotBlank() },
                    release = release(),
                ),
            scope = scope,
        )
    }
}

@JsFun("() => window.location.origin")
private external fun origin(): String

/**
 * Where katcher is, and which build this is — read from the page rather than compiled in.
 *
 * The page is generated by whoever deploys the bundle; the bundle is the same bytes for everyone.
 * A build identifier compiled into the wasm would make every deployment a different artefact, which
 * is the opposite of what a content-hashed bundle is for (D10).
 */
@JsFun("() => (globalThis.SHASHKI && globalThis.SHASHKI.tilesUrl) || ''")
private external fun tilesUrl(): String

@JsFun("() => (globalThis.SHASHKI && globalThis.SHASHKI.katcherUrl) || ''")
private external fun katcherUrl(): String

@JsFun("() => (globalThis.SHASHKI && globalThis.SHASHKI.katcherAppKey) || ''")
private external fun katcherAppKey(): String

@JsFun("() => (globalThis.SHASHKI && globalThis.SHASHKI.release) || 'dev'")
private external fun release(): String
